### PR TITLE
Handling missing icon

### PR DESCRIPTION
**Pull request by Skiepp**
In the process of adding a custom kind on the database (i.e. with a custom job) the **only one** blocker is the null pointer trown in the section below:
```js
const RepositoryIcon = (props: Props) => {
  if (!isUndefined(props.type) && props.type === 'white') {
    return <img alt="Icon" src={ICONS[props.kind][props.type]} className={props.className} />;
  } else {
    return (
      <>
        <img alt="Icon" src={ICONS[props.kind].default} className={`${props.className} iconLight`} /> <--- This line
        <img alt="Icon" src={ICONS[props.kind].white} className={`${props.className} iconDark`} />    <--- This line
      </>
    );
  }
};
```

Can we add a simple check before?
Being it trasnparent for the actual code, I think it could also be useful for some corner case of db migration as it prevents the entire page to just go blanks

Thaks a lot!

### CODE REVIEW

**Review by cynthia-sg — COMMENTED** [review]
Thanks 👍 

Could you add a test for this case?

**Comment by cynthia-sg** [comment]
Thanks, can you please rebase from master @Skiepp?

**Comment by Skiepp** [comment]
> Thanks, can you please rebase from master @Skiepp?

Done 👍

**Review by cynthia-sg — APPROVED** [review]
👍

**Pull request merged**
