### PR TITLE
Stop displaying production users links on pkg view

### PR DESCRIPTION
**Pull request by cynthia-sg**
Signed-off-by: Sergio Castaño Arteaga <tegioz@icloud.com>
Signed-off-by: Cintia Sanchez Garcia <cynthiasg@icloud.com>
Co-authored-by: Sergio Castaño Arteaga <tegioz@icloud.com>
Co-authored-by: Cintia Sanchez Garcia <cynthiasg@icloud.com>

### CODE REVIEW

**Review by tegioz — APPROVED** [review]

**Comment by mkilchhofer** [comment]
Hi 👋 

What's the story behind? Do you hide that section only temporary or is it a definitive decision? :-)

**Comment by tegioz** [comment]
Hi @mkilchhofer 👋

The goal of this feature was to give users more information so that they could make better decisions when picking an option among multiple similar choices. However, we've noticed recently that it was being used in some cases to improve some websites visibility. Some of those were appearing consistently in *all* the packages with most stars, being some of them online gambling sites. It's very unfortunate as it could have been very helpful, but we should also have predicted that a feature like this could easily be misused.

This doesn't have to be something definitive, not at all. We just wanted to address the issue as soon as possible and think carefully about it. Maybe a solution could be just to remove the links and leave the organizations names. Any ideas are welcome of course 🙂 We should have explained this in the PR, sorry about that.

**Comment by tegioz** [comment]
Please note that we keep displaying the total count though, we've just hidden the names and links.

Screen Shot 2022-05-10 at 17 16 32

**Comment by mkilchhofer** [comment]
Thanks alot for the clarification. 

Yup I already saw that there were "orgs" which were displayed on all packages I browsed/used.

**Pull request merged**
