### PR TITLE
trivy: clean environment variables when launching scanner

### PR DESCRIPTION
**Pull request by dirkmueller**
In the docker.io based case, the code was trying to add the environment
variables to include the dockerhub access credentials to avoid
rate-limiting. This however leads to an immediate failure with an error
message like "$HOME is not defined" instead of being able to scan
the image.

In all other cases we were passing down the full environment, which is
also not perfect. So reset environment to the known safe variables and
append the dockerhub access credentials when needed.

Signed-off-by: Dirk Mueller <dirk@dmllr.de>

### CODE REVIEW

**Review by tegioz — CHANGES_REQUESTED** [review]
Hi @dirkmueller

Thanks for reporting this issue and submitting a fix for it.

I'd rather passing to `trivy` only the environment variables it needs to do its job. There could be credentials or some other stuff in the main process environment that the `trivy` process shouldn't probably receive. Also, some could clash (now or eventually) and cause unintended side effects. So I think we should probably start by setting only `HOME`.

I'll try to reproduce this on my end as I haven't seen this happening before. It's scanning fine locally for me, as well as in the staging and production environments. But I'll double check just in case I've missed something, specially to verify that this is not affecting production.

Thanks again!

**Comment by dirkmueller** [comment]
@tegioz so the error I get is:

```
error running trivy on image artifacthub/db-migrator:v0.7.0: exit status 1: 2020-12-10T21:24:08.938+0100\t\x1b[31mFATAL\x1b[0m\tunable to initialize the docker scanner: 2 errors occurred:\n\t* unable to inspect the image (index.docker.io/artifacthub/db-migrator:v0.7.0): Error: No such image: index.docker.io/artifacthub/db-migrator:v0.7.0\n\t* .dockercfg: $HOME is not defined
````

it is possible that there is something specific to my environment causing this. 

> I'd rather passing to trivy only the environment variables it needs to do its job. There could be credentials or some other stuff in the main process environment that the trivy process shouldn't probably receive.

I hear you, but my patch didn't change that. it always passed all environment variables (because thats the default behavior), only in the case of replication from docker.io it deleted them by overwriting them with only these two. 

I'll see if I can fix the patch as you advised.

**Comment by tegioz** [comment]
> @tegioz so the error I get is:
> 
> ```
> error running trivy on image artifacthub/db-migrator:v0.7.0: exit status 1: 2020-12-10T21:24:08.938+0100\t\x1b[31mFATAL\x1b[0m\tunable to initialize the docker scanner: 2 errors occurred:\n\t* unable to inspect the image (index.docker.io/artifacthub/db-migrator:v0.7.0): Error: No such image: index.docker.io/artifacthub/db-migrator:v0.7.0\n\t* .dockercfg: $HOME is not defined
> ```
> 
> it is possible that there is something specific to my environment causing this.

Yes, it looks like it's something specific to your environment, but we should fix it anyway :)

> 
> > I'd rather passing to trivy only the environment variables it needs to do its job. There could be credentials or some other stuff in the main process environment that the trivy process shouldn't probably receive.
> 
> I hear you, but my patch didn't change that. it always passed all environment variables (because thats the default behavior), only in the case of replication from docker.io it deleted them by overwriting them with only these two.

Yes, you are right. That was happening before, and not only here but also when calling the `opm` external tool, you didn't introduce it. What I meant is that I think it'd be better if we pass only what trivy needs, setting the `HOME` at the beginning when setting up the command, and extending with the credentials when the registry is `docker.io`.

> 
> I'll see if I can fix the patch as you advised.

Thanks!

**Review by tegioz — COMMENTED** [review]
I think that looks great :)

Could you please move the block below up to the first section of the function where the cmd is prepared?

```go
// clean environment
cmd.Env = []string{
	"PATH=" + os.Getenv("PATH"),
	"USER=" + os.Getenv("USER"),
	"HOME=" + os.Getenv("HOME"),
}
```

Thanks!

**Review by tegioz — APPROVED** [review]
Thanks 👍

**Pull request merged**
