### PR TITLE
Added FinOps and Security Categories

### PR DESCRIPTION
**Pull request by Omkar0114**
#169

### CODE REVIEW

**Review by agardnerIT — DISMISSED** [review]
Looks good to me

**Comment by agardnerIT** [comment]
Please sign your commit so DCO bot doesn't complain and block the merge. Instructions [here](https://github.com/artifacthub/hub/pull/2277/checks?check_run_id=8194315560).

**Comment by Omkar0114** [comment]
Updated @agardnerIT :)

**Comment by tegioz** [comment]
Thanks for the PR @Omkar0114 @agardnerIT!

**Review by tegioz — APPROVED** [review]
👍

**Pull request merged**
